name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t builder docker/

    - name: Build apk
      run: |
        ./.github/workflows/build-ci.sh

    - name: Archive apk
      uses: actions/upload-artifact@v4
      with:
        name: openpilot-0.1-arm64-v8a-debug.aar
        path: bin/openpilot-0.1-arm64-v8a-debug.aar
